version: "3.9"

networks:
  web:
    external: true
  internal:
    external: true
  default:
    external: true
    name: internal

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      -  ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - "/disk/mosquitto/data/:/mosquitto/data"
      - "/disk/mosquitto/log/:/mosquitto/log"
