version: "3.9"

x-logging: &default-logging
  driver: loki
  options:
    loki-url: "http://127.0.0.1:3100/loki/api/v1/push"

networks:
  web:
    external: true
  internal:
    external: true
  default:
    external: true
    name: internal

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9380:80/tcp"
    env_file:
      - ./pihole/pihole.env
    volumes:
      # - "./pihole/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf"
      - "/disk/etc/pihole/:/etc/pihole/"
      - "/disk/etc/dnsmasq.d/:/etc/dnsmasq.d/"
    cap_add:
      - NET_ADMIN
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_NICE
      - CAP_IPC_LOCK
      - CAP_CHOWN
