version: "3.9"

networks:
  web:
    external: true
  internal:
    external: true
  default:
    external: true
    name: internal

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      -  ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - "/disk/mosquitto/data/:/mosquitto/data"
      - "/disk/mosquitto/log/:/mosquitto/log"

  postgres:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ./postgres/env.secret
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data