// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package main

import (
	"context"
	"time"
)

const addSensorData = `-- name: AddSensorData :exec
INSERT INTO living_room (
  time, temperature, humidity
) VALUES (
  $1, $2, $3
)
`

type AddSensorDataParams struct {
	Time        time.Time
	Temperature float64
	Humidity    float64
}

func (q *Queries) AddSensorData(ctx context.Context, arg AddSensorDataParams) error {
	_, err := q.db.ExecContext(ctx, addSensorData, arg.Time, arg.Temperature, arg.Humidity)
	return err
}
