- name: Setup my coreutils
  hosts: all
  become: false
  tasks:
    - name: Install packages
      community.general.pacman:
        state: present
        name:
          - vim
          - jq
          - curl
          - git
          - docker
          - docker-compose
          - fd
          - the_silver_searcher
          - fzf
          - bat
          - podman
          - podman-compose
          - git-crypt
          - chezmoi
          - htop
          - fish
          - fisher

    - name: Install fisher plugins
      ansible.builtin.command: fisher update
      become: true
      changed_when: false
