- name: Install Docker
  hosts: all
  become: false
  vars_prompt:
    - name: github_container_registry_token
      prompt: Enter your Github PAT
  tasks:
    - name: Install packages
      community.general.pacman:
        state: present
        name:
          - docker
          - docker-compose
          - podman
          - podman-compose

    - name: Set the docker logging to journald
      ansible.builtin.lineinfile:
        path: /etc/docker/daemon.json
        line: '{"log-driver": "journald"}'
        create: true
        state: present
        owner: root
        group: root
        mode: 0644
      become: true

    - name: Enable and start docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: true
      become: true

    - name: Log into ghcr.io
      community.docker.docker_login:
        registry_url: ghcr.io
        username: vhanda
        password: "{{ github_container_registry_token }}"
      become: true
